### PR TITLE
fix(search) : add height to the search container

### LINKED ISSUE #1: Search text box is buggy on FF
Hi !

I found an issue with my **Firefox ESR 60**.
The search box is not available (even with focus). Search component seems to not be render properly.

5c25f803-651d-4fcd-9470-40232516fd94

DOM of the header

```html
<div class="flex px-4 my-4 lg:px-16 lg:my-8 relative">
  <a href="/" class="flex-none router-link-active"
    ><img src="/img/project-types/vue.png" alt="Logo" class="w-8 h-8 rounded"
  /></a>
  <div class="flex-1"></div>
  <a
    href="/pkg/add?projectTypeId=244960085436006912"
    class="inline-block cursor-pointer text-center relative rounded select-none outline-none px-4 py-1 text-gray-600 hover:text-gray-500 mr-4"
    type="button"
    tabindex="0"
    role="button"
    ><div class="flex items-center justify-center rounded">
      <i class="material-icons text-lg mr-2">add</i> Add package
      <!---->
    </div>
    <!----></a
  >
  <div>
    <div class="w-8 h-8 flex items-center justify-center">
      <a href="/me/" class=""
        ><img
          src="https://avatars3.githubusercontent.com/u/2922851?v=4"
          alt="User"
          class="max-w-full max-h-full rounded-full bg-gray-700"
      /></a>
    </div>
  </div>
  <div class="absolute top-0 left-0 w-full h-0 flex justify-center">
    <button
      type="button"
      tabindex="0"
      role="button"
      class="inline-block cursor-pointer text-center relative rounded select-none outline-none px-4 py-1 text-gray-600 hover:text-gray-500"
    >
      <div class="flex items-center justify-center rounded">
        <i class="material-icons text-lg mr-2">search</i> Search...
        <!---->
      </div>
      <!---->
    </button>
  </div>
</div>
```

### PR DESCRIPTION
**Pull request by edimitchel**
Fix #1

### CODE REVIEW

**Comment by Akryum** [comment]
Deploy preview should finally be working correctly :sweat_smile:

**Comment by Akryum** [comment]
(Signing in isn't working yet outside of production because of OAuth callback URL)

**Comment by Akryum** [comment]
The issue with the fix is that other buttons on the header are not clickable on the top half of the header because the div is in absolute position. :(

**Comment by edimitchel** [comment]
Argh. I'll find a solution! ;)

**Comment by Akryum** [comment]
I've already pushed a solution in the PR, please try the deploy preview and check if your issue is solved :)

**Pull request closed without merging**
